### ISSUE TITLE
New stemmers

### ISSUE THREAD

**Issue by dzieciou** [sheerun/awesome-polish-nlp#3]
Hi!

I have ported Stempel Stemmer from Java to Python and pretrained it on a larger dictionary: https://github.com/dzieciou/pystempel. Understemming error decreased and average accuracy in some of my information retrieval tasks has improved thanks to that.

During my research on stemmers for Polish I have found also others. You may find them listed in the "Alternatives" section of my project README.

**Comment by sheerun** [comment]
Could you send PR?

**Comment by dzieciou** [comment]
@sheerun Added in #4

**Comment by sheerun** [comment]
thank you!
